"""
DO NOT EDIT THIS FILE MANUALLY; THIS IS JUST A COPY OF THE CODE IN LAMBDA FOR FUTURE REFERENCE.
The Lambda function does the following:
- Sends emails via Amazon SES to verified email addresses,
- Updates reminder status to 'sent' or 'failed' in Supabase, 
- Updates records in reminder_notifications in Supabase

Commands run to build and deploy:
```
cat > requirements.txt << 'EOF'                                                               
supabase==2.9.0
boto3                              
EOF

pip install \                                                                                 
  --platform manylinux2014_x86_64 \
  --target . \
  --implementation cp \
  --python-version 3.11 \
  --only-binary=:all: \
  --upgrade \
  -r requirements.txt

zip -r reminder_lambda.zip .

ls -lh reminder_lambda.zip

And then upload reminder_lambda.zip to AWS Lambda console, deploy and test the code.
```
An Eventbridge rule triggers this Lambda function every minute to check for due reminders.
"""

import json
import os
from datetime import datetime, timezone
from uuid import uuid4
import boto3
from supabase import create_client, Client

# Initialize SES client
ses_client = boto3.client('ses', region_name='ap-southeast-1')

# Supabase client singleton
_supabase_client = None

def get_supabase_client() -> Client:
    global _supabase_client
    
    if _supabase_client is None:
        url = os.environ['SUPABASE_URL']
        key = os.environ['SUPABASE_KEY']
        
        if not url or not key:
            raise ValueError("SUPABASE_URL and SUPABASE_KEY must be set")
        
        _supabase_client = create_client(url, key)
        print("Supabase client initialized")
    
    return _supabase_client

SENDER_EMAIL = os.environ.get('SENDER_EMAIL')

def parse_description(description: str) -> dict:
    """
    Parse description - either JSON format from tool or plain text fallback
    
    Returns dict with: subject, body, task, type
    """
    try:
        # Try parsing as JSON first (new format from tool)
        data = json.loads(description)
        return {
            'subject': data.get('subject', 'Reminder from Casa Amigo'),
            'body': data.get('body', description),
            'task': data.get('task', ''),
            'type': data.get('type', '')
        }
    except (json.JSONDecodeError, TypeError):
        # Fallback for plain text descriptions (legacy format)
        return {
            'subject': f'Reminder: {description}',
            'body': f'This is a friendly reminder about: {description}',
            'task': description,
            'type': ''
        }

def lambda_handler(event, context):
    """Check for due reminders and send email notifications"""
    try:
        print("Starting reminder check...")
        
        supabase = get_supabase_client()
        now = datetime.now(timezone.utc).isoformat()
        
        # Query reminders that are due with user email
        response = supabase.table('reminders').select(
            '''
            reminder_id,
            user_id,
            description,
            reminder_date,
            users:users (
                email_id
            )
            '''
        ).lte('reminder_date', now).eq('status', 'active').execute()
        
        reminders = response.data
        
        if not reminders:
            print("No reminders to send")
            return {
                'statusCode': 200,
                'body': json.dumps({'message': 'No reminders to send'})
            }
        
        print(f"Found {len(reminders)} reminders to process")
        
        sent_count = 0
        failed_count = 0
        
        for reminder in reminders:
            try:
                reminder_id = reminder['reminder_id']
                user_id = reminder['user_id']
                description = reminder['description']
                reminder_date = reminder['reminder_date']

                # Get user email from joined users relationship
                user_info = reminder.get('users')
                user_email = user_info.get('email_id') if user_info else None

                # Fallback lookup if join didn't work
                if not user_email and reminder.get('user_id'):
                    result = supabase.table('users').select('email_id').eq('user_id', reminder['user_id']).single().execute()
                    if result.data:
                        user_email = result.data['email_id']
                
                # Parse description (handles both JSON and plain text)
                email_content = parse_description(description)
                
                # Send email with structured content
                send_email_notification(
                    user_email, 
                    email_content['subject'],
                    email_content['body'],
                    reminder_date
                )
                
                # Create notification record
                notification_data = {
                    'notification_id': str(uuid4()),
                    'reminder_id': reminder_id,
                    'user_id': user_id,
                    'delivery_status': 'sent',
                    'sent_at': datetime.now(timezone.utc).isoformat(),
                    'metadata': {
                        'email': user_email,
                        'method': 'ses',
                        'subject': email_content['subject']
                    }
                }
                
                supabase.table('reminder_notifications').insert(notification_data).execute()
                
                # Update reminder status
                supabase.table('reminders').update({
                    'status': 'sent',
                    'last_sent': datetime.now(timezone.utc).isoformat(),
                    'updated_at': datetime.now(timezone.utc).isoformat()
                }).eq('reminder_id', reminder_id).execute()
                
                print(f"✓ Successfully sent reminder {reminder_id} to {user_email}")
                sent_count += 1
                
            except Exception as e:
                print(f"✗ Failed to send reminder {reminder.get('reminder_id')}: {str(e)}")
                mark_reminder_failed(supabase, reminder.get('reminder_id'), reminder.get('user_id'), str(e))
                failed_count += 1
        
        result = {
            'message': f'Processed {len(reminders)} reminders',
            'sent': sent_count,
            'failed': failed_count
        }
        
        print(f"Processing complete: {result}")
        
        return {
            'statusCode': 200,
            'body': json.dumps(result)
        }
        
    except Exception as e:
        print(f"Error in lambda_handler: {str(e)}")
        import traceback
        traceback.print_exc()
        return {
            'statusCode': 500,
            'body': json.dumps({'error': str(e)})
        }

def mark_reminder_failed(supabase, reminder_id, user_id, error_msg):
    """Mark a reminder as failed and create notification record"""
    try:
        notification_data = {
            'notification_id': str(uuid4()),
            'reminder_id': reminder_id,
            'user_id': user_id,
            'delivery_status': 'failed',
            'sent_at': datetime.now(timezone.utc).isoformat(),
            'metadata': {'error': error_msg}
        }
        supabase.table('reminder_notifications').insert(notification_data).execute()
        
        supabase.table('reminders').update({
            'status': 'failed',
            'updated_at': datetime.now(timezone.utc).isoformat()
        }).eq('reminder_id', reminder_id).execute()
    except Exception as e:
        print(f"Failed to mark reminder as failed: {str(e)}")

def send_email_notification(user_email: str, subject: str, body: str, reminder_date: str):
    """Send email notification via Amazon SES with custom subject and body"""
    
    # Use custom subject from description or default
    email_subject = subject if subject else "🔔 Reminder from Casa Amigo"
    
    # Build email body with custom content (without date)
    body_text = f"""
Hello,

{body}

Best regards,
Casa Amigo Team

---
Casa Amigo - Your Rental Assistant
This is an automated reminder from your Casa Amigo chatbot.
    """.strip()
    
    body_html = f"""
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<style>
    body {{
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
        line-height: 1.6;
        color: #333;
        margin: 0;
        padding: 0;
        background-color: #f5f5f5;
    }}
    .container {{
        max-width: 900px;
        margin: 20px auto;
        background: #ffffff;
        border-radius: 8px;
        overflow: hidden;
        box-shadow: 0 2px 8px rgba(0,0,0,0.08);
    }}
    .header {{
        background: linear-gradient(135deg, #2C4B8E 0%, #D84339 100%);
        color: white;
        padding: 40px 48px;
        text-align: center;
    }}
    .header h1 {{
        margin: 0 0 8px 0;
        font-size: 32px;
        font-weight: 700;
    }}
    .header p {{
        margin: 0;
        font-size: 16px;
        opacity: 0.95;
    }}
    .content {{
        padding: 48px;
    }}
    .greeting {{
        font-size: 18px;
        color: #333;
        margin-bottom: 24px;
    }}
    .reminder-body {{
        font-size: 18px;
        line-height: 1.7;
        margin: 24px 0;
        padding: 28px;
        background: #f9fafb;
        border-left: 4px solid #D84339;
        border-radius: 6px;
        color: #1a1a1a;
    }}
    .signature {{
        margin-top: 36px;
        padding-top: 24px;
        border-top: 1px solid #e5e7eb;
        font-size: 16px;
        color: #555;
    }}
    .signature-name {{
        font-weight: 600;
        color: #2C4B8E;
        margin-bottom: 4px;
    }}
    .footer {{
        background: #f9fafb;
        text-align: center;
        padding: 24px 48px;
        border-top: 1px solid #e5e7eb;
    }}
    .footer-title {{
        font-size: 15px;
        font-weight: 600;
        color: #2C4B8E;
        margin-bottom: 6px;
    }}
    .footer-text {{
        font-size: 13px;
        color: #666;
        line-height: 1.5;
    }}
    
    /* Mobile responsiveness */
    @media only screen and (max-width: 640px) {{
        .container {{
            margin: 10px;
            border-radius: 6px;
        }}
        .header {{
            padding: 32px 24px;
        }}
        .header h1 {{
            font-size: 24px;
        }}
        .header p {{
            font-size: 14px;
        }}
        .content {{
            padding: 28px 20px;
        }}
        .greeting {{
            font-size: 16px;
        }}
        .reminder-body {{
            font-size: 16px;
            padding: 20px;
        }}
        .signature {{
            font-size: 15px;
        }}
        .footer {{
            padding: 20px 20px;
        }}
    }}
</style>
</head>
<body>
<div class="container">
    <div class="header">
        <h1>🏠 Casa Amigo</h1>
        <p>Your Rental Assistant</p>
    </div>
    <div class="content">
        <div class="greeting">Hello there! 👋</div>
        <div class="reminder-body">
            {body}
        </div>
        <div class="signature">
            <div class="signature-name">Best regards,</div>
            <div>The Casa Amigo Team</div>
        </div>
    </div>
    <div class="footer">
        <div class="footer-title">Casa Amigo</div>
        <div class="footer-text">
            Simplifying rentals, one chat at a time.<br>
            This is an automated reminder from your Casa Amigo chatbot.
        </div>
    </div>
</div>
</body>
</html>
    """.strip()
    
    response = ses_client.send_email(
        Source=SENDER_EMAIL,
        Destination={
            'ToAddresses': [user_email]
        },
        Message={
            'Subject': {
                'Data': email_subject,
                'Charset': 'UTF-8'
            },
            'Body': {
                'Text': {
                    'Data': body_text,
                    'Charset': 'UTF-8'
                },
                'Html': {
                    'Data': body_html,
                    'Charset': 'UTF-8'
                }
            }
        }
    )
    
    print(f"SES email sent to {user_email}: {response['MessageId']}")
    return response